# Selecting Rows and Columns in pandas

### 1. Reading Data
We first import `pandas` and load a table into a DataFrame.

In [4]:
import pandas as pd

df = pd.read_csv('population.csv', index_col=0)

### 2. Attributes and Methods

`.shape` is an *attribute*. It can be used with any dataset using a dot. It shows the number of rows and columns in a DataFrame as a Python *tuple*:

In [5]:
df.shape

(275, 81)

`.head()` is a *method*. It can be called on any DataFrame object by the dot, followed by parentheses.
It returns the first N rows of the DataFrame.

In [6]:
df.head(3)

                            1800       1810  ...        2014        2015
Total population                             ...
Abkhazia                     NaN        NaN  ...         NaN         NaN
Afghanistan            3280000.0  3280000.0  ...  31627506.0  32526562.0
Akrotiri and Dhekelia        NaN        NaN  ...         NaN         NaN

[3 rows x 81 columns]

### 3. Selecting Rows and Columns
Match the Python commands with the descriptions below.

* remove rows with missing values
* select a single row
* inspect column labels
* select multiple columns
* select rows by position
* select rows that match a condition
* select multiple rows
* select a single column
* select values in a given range
* select rows and columns by position
* inspect row labels
* select rows and columns

Create new Markdown cells in the notebook to have a heading for each command.

**inspect row labels**

In [8]:
df.index

Index(['Abkhazia', 'Afghanistan', 'Akrotiri and Dhekelia', 'Albania',
       'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla',
       'Antigua and Barbuda',
       ...
       'British Indian Ocean Territory', 'Clipperton',
       'French Southern and Antarctic Lands', 'Gaza Strip',
       'Heard and McDonald Islands', 'Northern Marianas',
       'South Georgia and the South Sandwich Islands',
       'US Minor Outlying Islands', 'Virgin Islands', 'West Bank'],
      dtype='object', name='Total population', length=275)

**inspect column labels**

In [9]:
df.columns

Index(['1800', '1810', '1820', '1830', '1840', '1850', '1860', '1870', '1880',
       '1890', '1900', '1910', '1920', '1930', '1940', '1950', '1951', '1952',
       '1953', '1954', '1955', '1956', '1957', '1958', '1959', '1960', '1961',
       '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970',
       '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988',
       '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015'],
      dtype='object')

**select a single column**

In [11]:
df['2015']

Total population
Abkhazia                                               NaN
Afghanistan                                     32526562.0
Akrotiri and Dhekelia                                  NaN
Albania                                          2896679.0
Algeria                                         39666519.0
                                                   ...
Northern Marianas                                      NaN
South Georgia and the South Sandwich Islands           NaN
US Minor Outlying Islands                              NaN
Virgin Islands                                         NaN
West Bank                                              NaN
Name: 2015, Length: 275, dtype: float64

**select multiple columns**

In [12]:
df[['1900', '1950', '2000']]

                                                   1900       1950        2000
Total population
Abkhazia                                            NaN        NaN         NaN
Afghanistan                                   5021241.0  7752118.0  19701940.0
Akrotiri and Dhekelia                               NaN    10661.0     15157.0
Albania                                        819950.0  1263171.0   3121965.0
Algeria                                       4946166.0  8872247.0  31183658.0
...                                                 ...        ...         ...
Northern Marianas                                   NaN        NaN         NaN
South Georgia and the South Sandwich Islands        NaN        NaN         NaN
US Minor Outlying Islands                           NaN        NaN         NaN
Virgin Islands                                      NaN        NaN         NaN
West Bank                                           NaN        NaN         NaN

[275 rows x 3 columns]

**select a single row**

In [7]:
df.loc['Estonia']

1800     334136.0
1810     334136.0
1820     342427.0
1830     366799.0
1840     402035.0
          ...
2011    1328068.0
2012    1324040.0
2013    1320050.0
2014    1316203.0
2015    1312558.0
Name: Estonia, Length: 81, dtype: float64

**select multiple rows**

In [13]:
df.loc[['Japan', 'China', 'Brazil']]

                         1800         1810  ...          2014          2015
Total population                            ...
Japan              30294378.0   30645903.0  ...  1.267946e+08  1.265735e+08
China             321675013.0  350542958.0  ...  1.369436e+09  1.376049e+09
Brazil              3639636.0    4058652.0  ...  2.060779e+08  2.078475e+08

[3 rows x 81 columns]

**select rows and columns**

In [14]:
df.loc['Croatia', '2000']

4428069.0

**select rows by position**

In [15]:
df.iloc[10:15]

                       1800       1810  ...        2014        2015
Total population                        ...
Argentina          534000.0   534000.0  ...  42980026.0  43416755.0
Armenia            413326.0   413326.0  ...   3006154.0   3017712.0
Aruba               19286.0    19286.0  ...    103441.0    103889.0
Australia          351014.0   342440.0  ...  23622353.0  23968973.0
Austria           3205587.0  3286650.0  ...   8516916.0   8544586.0

[5 rows x 81 columns]

**select rows and columns by position**

In [16]:
df.iloc[10:15, 75:]

                        2010        2011  ...        2014        2015
Total population                          ...
Argentina         41222875.0  41655616.0  ...  42980026.0  43416755.0
Armenia            2963496.0   2967984.0  ...   3006154.0   3017712.0
Aruba               101597.0    101936.0  ...    103441.0    103889.0
Australia         22162863.0  22542371.0  ...  23622353.0  23968973.0
Austria            8391986.0   8423559.0  ...   8516916.0   8544586.0

[5 rows x 6 columns]

**select rows that match a condition**

In [17]:
df.loc[df['2000'] > 200_000_000]

                         1800         1810  ...          2014          2015
Total population                            ...
China             321675013.0  350542958.0  ...  1.369436e+09  1.376049e+09
India             168574895.0  171940819.0  ...  1.295292e+09  1.311051e+09
Indonesia          16108545.0   16537268.0  ...  2.544548e+08  2.575638e+08
United States       6801854.0    8294928.0  ...  3.194486e+08  3.217736e+08
USSR                      NaN          NaN  ...           NaN           NaN

[5 rows x 81 columns]

**select values in a given range**

In [18]:
df[df['2000'].between(500_000, 1_000_000)]

                       1800      1810  ...       2014       2015
Total population                       ...
Bahrain             64474.0   64474.0  ...  1361930.0  1377237.0
Bhutan              89989.0   89989.0  ...   765008.0   774830.0
Comoros             56346.0   56346.0  ...   769991.0   788474.0
Cyprus             184392.0  184590.0  ...  1153658.0  1165300.0
Djibouti            22848.0   22848.0  ...   876174.0   887861.0
Equatorial Guinea   80377.0   80377.0  ...   820885.0   845060.0
Fiji               130533.0  132682.0  ...   886450.0   892145.0
Guyana             166034.0  166034.0  ...   763893.0   767085.0
Montenegro         126582.0  126582.0  ...   625292.0   625781.0
Qatar               14092.0   14092.0  ...  2172065.0  2235355.0
Reunion             92744.0   92744.0  ...   855177.0   861154.0
Timor-Leste        137262.0  137262.0  ...  1157360.0  1184765.0

[12 rows x 81 columns]

**remove rows with missing values**

In [10]:
df.dropna()

                            1800       1810  ...        2014        2015
Total population                             ...
Afghanistan            3280000.0  3280000.0  ...  31627506.0  32526562.0
Albania                 410445.0   423591.0  ...   2889676.0   2896679.0
Algeria                2503218.0  2595056.0  ...  38934334.0  39666519.0
American Samoa            8170.0     8156.0  ...     55434.0     55538.0
Andorra                   2654.0     2654.0  ...     72786.0     70473.0
...                          ...        ...  ...         ...         ...
Virgin Islands (U.S.)    40000.0    40000.0  ...    106208.0    106291.0
Yemen                  2593000.0  2593000.0  ...  26183676.0  26832215.0
Zambia                  747000.0   747000.0  ...  15721343.0  16211767.0
Zimbabwe               1085814.0  1085814.0  ...  15245855.0  15602751.0
South Sudan            1027378.0  1041076.0  ...  11911184.0  12339812.0

[229 rows x 81 columns]

## License
(c) 2017 Kristian Rother.
Distributed under the conditions of the MIT License.